### ISSUE TITLE
Caching requests?

### ISSUE THREAD

**Issue by supermoos** [contentful/ContentfulBundle#10]
Is there a preferred way to setup caching of requests with Contentful and Symfony, so that one won't hit the API usage limit so quickly?

**Comment by realityking** [comment]
Hi @supermoos! The Bundle supports caching the requests for the space and content types. It's currently not well documented - sorry about that - but you can see it in this example: https://github.com/contentful/product-catalogue-app-symfony/blob/292b79fb8fe9fd41d02432097e2a121a5e085199/app/config/config.yml#L45

If you activate that a cache warmup will fetch these objects and store them on disk. Note that the cache is not build incrementally and if you want to update them with changes made in Contentful you have to re-warm the cache.

We currently don't support caching for entries and assets in our SDKs as we have no means of invalidating that cache. Some users have made use of the ability to inject a custom Guzzle instance to create their own caching. The other alternative is to serialise the objects to JSON and then us `Client::reviveJson` when you fetch from that cache.

Personally, I'd see if you actually end up going over the API limits significantly. Most users stay way under what their plans include and if you do go over the additional usage shouldn't break the bank. If it does become a problem you could still add a caching solution.
