### ISSUE TITLE
How to set defaultLocale on the client?

### ISSUE THREAD

**Issue by supermoos** [contentful/ContentfulBundle#11]
The PHP SDK has support for setting the locale for the entire client instead of just an entry (which annoyingly doesn't set it for an entries linkes entries) , how would you do this in contentful without using `default_locale` in the config. I need it to be set dynamically based on a URL param.

```
        $client = $this->get('contentful.delivery');
        $entry = $client->getEntry('yadadada');
        $entry->setLocale('de-DE');
```

**Comment by realityking** [comment]
Hi @supermoos!

That's not possible as the PHP SDK only allows setting the default locale when constructing the Client, not afterwards. Even it it was possible I wouldn't recommend doing it as you would make a service dependent on the request which is now considered an anti-pattern.

Instead I'd recommend you set the locale when you retrieve the entries. When requesting a single entry you just add the locale as the [second parameter](https://github.com/contentful/contentful.php/blob/5a5c4043ce94fd967e4d1f67ffcaa91e70fb051f/src/Delivery/Client.php#L192), when requesting a collection you set it on the [query object](https://github.com/contentful/contentful.php/blob/5a5c4043ce94fd967e4d1f67ffcaa91e70fb051f/src/Delivery/Query.php#L77). This way you get the best of both worlds, an object graph for a single locale and no state that persists between requests.

Thinking through this question I unfortunately discovered contentful/contentful.php#109, be aware of that limitation when you implement this strategy.

Does that solve your issue?

**Comment by realityking** [comment]
Hi @supermoos,

I'm closing this issue for now. Feel free to reopen it if you have any more questions.
