### ISSUE TITLE
Add support for Symfony 4

### ISSUE THREAD

**Issue by prudentmildew** [contentful/ContentfulBundle#21]
Hi,

Do you plan to add support for Symfony 4?

Thanks in advance.

Best regards,
Erland Glad Solstrand

**Comment by dborsatto** [comment]
Hey,

yes, adding Symfony 4 support is definitely in my todo list. I'm actually using Symfony 4 on a project right now, so I'm already experimenting with it and seeing what I would have to do in order to add support. Hopefully, I'll have more info about it soon 🙂

**Comment by prudentmildew** [comment]
Thanks for answering so fast! :)

I look forward to seeing the results.

/Erland
