### ISSUE TITLE
Make prod environment work without depending on profiler

### ISSUE THREAD

**Issue by RicardoNeves** [contentful/ContentfulBundle#3]
On development my app runs without no problem but when I go to production environment, if I don't enable the profiler on config.yml I get the following error message:

> The service "contentful.profiler_controller" has a dependency on a non-existent service "profiler"

It would be nice to make it work on production without depending on the profiler.

**Comment by realityking** [comment]
Thanks for the ticket! This should be fixed in master thanks to #2. There should be another stable release at the end of this or the beginning of the next week.

**Comment by Avariya** [comment]
Hi, @realityking, can you please create a release for version with fixed profiler. Because it is very impotent bugfix for using contentful bundle at prod env. As for me - using dev-master is not an option.

**Comment by realityking** [comment]
Hi @Avariya,
I just tagged [0.6.2-beta](https://github.com/contentful/ContentfulBundle/releases/tag/0.6.2-beta) that includes this fix.

**Comment by Avariya** [comment]
Thank you, @realityking !
