### ISSUE TITLE
Support for Symfony 2.8 (LTS)

### ISSUE THREAD

**Issue by Jan0707** [contentful/ContentfulBundle#31]
Hey folks,

I was just browsing your code and wondering what kept you from supporting SF2.8 ? On a glance, I could not find anything that would not work in SF2.8.

Cheers!

Jan

**Comment by dborsatto** [comment]
Hey @Jan0707,

there were a few reasons for choosing 3.4 as the minimum required version:
- It's the most recent LTS release.
- The cache component was added in 3.1, and it's used in this bundle. While you could make it work on a previous version (I've never actually tried it, but I suppose you can), requiring 3.4 allows me to assume it's there without bringing in extra dependencies.
- Some classes in the DI component were changed in 3.3 (and removed in 4.0). This means that the code would have to deal with 2 ways of handling configuration for the DI container, which would result in an ever more complex coonfiguration.
- Philosophical reasons: we want to try to push adoption of recent releases. Symfony is great at releasing minor versions without BC breaks. Using an LTS release shouldn't mean being "stuck" until that version is not supported any more, but rather be able to continuously move from one LTS to the next. And given that 3.4 has been out for quite a while, it made sense for us to make this call.

One last comment: this bundle is just an abstraction layer on top of the [contentful.php SDK](https://github.com/contentful/contentful.php), with a couple small extras (integration with the Symfony profiler, and cache warming). Working with the SDK without this bundle is perfectly possible, and that's actually what is done in our [PHP example application](https://github.com/contentful/the-example-app.php). That application required support for injecting credentials at runtime, something which would have been tricky to do using this bundle, so I actually decided not to use. And as you can see, it's not that complex 🙂 

Cheers,

Davide

**Comment by Jan0707** [comment]
Thank you :) That was a very informed response !
