### ISSUE TITLE
Update recipe for V4

### ISSUE THREAD

**Issue by Rabot18** [contentful/ContentfulBundle#35]
Hello,

I've upgraded contenful to v4 and I see that the recipe is still from contrib repository.

Could you "upgrade" it ? Or i have to do something on my side ?

` WARNING  contentful/contentful-bundle (>=4.0): From github.com/symfony/recipes-contrib:master
    The recipe for this package comes from the "contrib" repository, which is open to community contributions.
    Review the recipe at https://github.com/symfony/recipes-contrib/tree/master/contentful/contentful-bundle/4.0`

**Comment by pgrigoruta** [comment]
@Rabot18 , there is no error per se, this is a contributed recipe and Flex will always present this warning. If you are not receving any other error, you should be fine with pressing y and finishing up the install.
