### ISSUE TITLE
CacheWarmer and CacheClearer are not compatible with Symfony 3 and Syfmony 4

### ISSUE THREAD

**Issue by emodric** [contentful/ContentfulBundle#44]
This is due to `Contentful\ContentfulBundle\Cache\Delivery\CacheWarmer::warmUp` `Contentful\ContentfulBundle\Cache\Delivery\CacheClearer::clear` using `string` typehints for arguments, thus causing fatal errors, while said methods in Symfony 3.4 and 4.4 miss the typehint.

Removing typehints would be enough, since you can remove parameter typehints in extending classes (contravariance), but you cannot add them if parent doesn't have them.

https://3v4l.org/Xl2Oc

I haven't tested all parts of the bundle, so there may be more instances of issues like this.

**Comment by pgrigoruta** [comment]
Thanks @emodric makes sense. We just pushed a patch release to address this issue.

**Comment by emodric** [comment]
Thanks!
