### ISSUE TITLE
Typehint causing build error in Symfony 3.4 - 4.4

### ISSUE THREAD

**Issue by phillyfan36** [contentful/ContentfulBundle#46]
https://github.com/contentful/ContentfulBundle/blob/9ebbf92865a5f109ae9958abe2ec191636fcf391/src/DataCollector/Delivery/ClientDataCollector.php#L52

In Symfony v3.4 we get a PHP compile error because the ClientDataCollector declaration does not match the Symfony DataCollector it extends. The `collect` method typehints the $exception variable to be `\Exception` rather than `\Throwable`.

In this case, the typehint should be removed in order to be compatible with supported versions of this bundle.

**Comment by pgrigoruta** [comment]
Thanks @phillyfan36 , we just fixed this in the latest 6.0.3 release.
