### ISSUE TITLE
Null fields on cached entries

### ISSUE THREAD

**Issue by celikezer** [contentful/ContentfulBundle#50]
Hi.

I am trying to cache all of my contents so I enabled both the `runtime` and `content` option first request has no problems all of the contents are generated by my factories.

The problem is the second request, I am caching entry ID(s) which I called before but when I tried to retrieve with `$contentful->getEntry($id)` all of the fields are null! But I guess the entry must exist with its own fields in the Contentful`s own cache pool am I wrong?

This problem occurs when I enabled both of the `cache` and `runtime` options enabled.

**Comment by pgrigoruta** [comment]
Hi @ahmetcelikezer , first, I want to make sure you are aware of our documentation around caching - https://www.contentful.com/developers/docs/php/tutorials/caching-in-the-php-cda-sdk/ . 

Also, see https://github.com/contentful/contentful.php/blob/master/tests/E2E/CacheTest.php for various examples on cache implementations (part of our E2E tests). I think testCachedContentAutoWarmupWithEntriesAndAssets is closer to what you need. See if you can spot any differences between this and your implementation that can help you fix the issue.

If this does not help, please provide me with a code sample, as small as possible, but large enough so I can run it and reproduce the issue. I will be happy to further assist.

**Comment by celikezer** [comment]
Hi @pgrigoruta,

I am caching all the required blog post content ids by their category in the Redis like bellow:

```php
    <?php

    /** @return iterable<Post> **/
    public function getPostsByCategory(string $slug, int $limit = 100, int $skip = 0): iterable
    {
        $query = (new Query())
            ->setContentType(Post::CONTENT_TYPE)
            ->where('fields.category', $category)
            ->orderBy('-fields.publishDate')
            ->setLocale($this->locale)
            ->setLimit($limit)
            ->setSkip($skip)
        ;

        $entries = $this->contentfulClient->getEntries($query)->getItems();

        // Post class is the DTO and create is a static factory method
        $posts = array_map(static fn (Entry $entry) => Post::create($entry), $entries);

       $this->cachePosts($posts, $category, $limit, $skip);

        return array_filter($posts);
    }

    private function getCachedPosts(string $category, int $limit, int $skip): array
    {
        $postIdList = $this->cache->get(sprintf('%s_%s_%s__%s', $category, $limit, $skip, $this->locale));

        return array_map(fn (string $id) => $this->contentfulClient->getEntry($id, $this->locale), $postIdList);
    }

    private function cachePosts(iterable $posts, string $category, int $limit, int $skip): void
    {
        foreach($posts as $post) {
            $this->cache->set(
                sprintf('%s_%s_%s__%s', $category, $limit, $skip, $this->locale),
                $post->getId()
            ); 
        }
    }
```
> This is the sample code, but really close the original one.

You can see the sample code up there the problem is I  am checking if I am cached the list of id(s) with has if exists in the cache I am calling the `getCachedPosts` function, so it returns all the `Contentful\Delivery\Resource\Entry` objects but each object only contains the id property, fields are empty array.

When I disable `runtime` or the `content` cache option everything is working just fine. (I disabled `runtime` currently).

I can give more details if I am not clear enough.
