### ISSUE TITLE
No PHP8 support

### ISSUE THREAD

**Issue by wlasnapl** [contentful/ContentfulBundle#52]
Package doesn't support PHP8 so can't be used with PHP8 projects

**Comment by Sebb767** [comment]
Hi @wlasnapl ,

I'm working on verifying and updating all libraries at the moment.  The update should be released by the end of the week :)

**Comment by Sebb767** [comment]
Hi @wlasnapl ,

I just released version 6.2.0, which adds php8 support. Thank you for your patience! :)
