### ISSUE TITLE
Symfony 6 support

### ISSUE THREAD

**Issue by mdubbelman** [contentful/ContentfulBundle#53]
Could you please add support for Symfony 6? It has just been released and this package and contentful/contentful-management are the only packages that are holding us back from updating to Symfony 6.

Thanks!

**Comment by Sebb767** [comment]
Hi @mdubbelman ,

that shouldn't be a big problem :) I'll just need to check for breaking changes and ping you once the new version is released.

**Comment by mdubbelman** [comment]
Nice! Thanks!

**Comment by wlasnapl** [comment]
also waiting for Symfony 6 update, so good luck and let us know when it is ready

**Comment by wlasnapl** [comment]
@Sebb767 is there some progress with that?

**Comment by Sebb767** [comment]
> @Sebb767 is there some progress with that?

The review is finished, I'll release the updates for the four libraries today and tomorrow

**Comment by Sebb767** [comment]
Hi,

Sorry for the additional delay! As written in the other issue, with [contentful-management version 4.0](https://github.com/contentful/contentful-management.php/releases/tag/4.0.0) and [ContentfulBundle version 7.0](https://github.com/contentful/ContentfulBundle/releases/tag/7.0.0) you're now able to use Symfony 6. These versions contain some (minor) breaking changes, so be sure to check the release notes :)

EDIT: Fixed the release link
