### ISSUE TITLE
Symfony 5.4 LTS is not end of life

### ISSUE THREAD

**Issue by etiennenoel** [contentful/ContentfulBundle#55]
In this commit:
https://github.com/contentful/ContentfulBundle/commit/2f204f18f00246fcde07cc8f136f41c80e1eb0c4

Confirmed by the wording here:
https://github.com/contentful/ContentfulBundle/commit/c0ef01e5b981cd091da5f0f4898401150ffe2208

I can see that it's mentioned that Symfony 5 is end of life but that's not true. https://symfony.com/releases/5.4

Symfony 5.4 is LTS and this latest changes his preventing me from upgrading to the latest contentfulbundle version.

**Comment by wlasnapl** [comment]
And changes done for Symfony 6 should also work for Symfony 5.4

**Comment by Sebb767** [comment]
You're right - I'll check the compatibility and re-add support in the next version.

**Comment by Sebb767** [comment]
With [7.1.0](https://github.com/contentful/ContentfulBundle/releases/tag/7.1.0) we added support for it again :) Sorry for the trouble!
