### ISSUE TITLE
Support Client withQueryCache

### ISSUE THREAD

**Issue by mmenozzi** [contentful/ContentfulBundle#56]
Add support for the new `Client::withQueryCache()` method added in version [6.4.0 of contentful/contentful](https://github.com/contentful/contentful.php/releases/tag/6.4.0).

@Sebb767 feel free to assign this issue to me. I'll do it ASAP.

**Comment by Sebb767** [comment]
Simply open a PR and I'll merge+release it :)

Thank you!

**Comment by mmenozzi** [comment]
Hi @Sebb767, the [PR](https://github.com/contentful/ContentfulBundle/pull/66) has been open by @lruozzi9 3 weeks ago. Could you please merge it?
