### ISSUE TITLE
Deprecation warnings in PHP 8.1

### ISSUE THREAD

**Issue by dbebawy-modus** [contentful/ContentfulBundle#60]
1. Method "Symfony\Component\Console\Command\Command::execute()" might add "int" as a native return type declaration in the future. Do the same in child class "Contentful\ContentfulBundle\Command\Delivery\InfoCommand" now to avoid errors or add an explicit @return annotation to suppress this message.
1. Method "Symfony\Component\Console\Command\Command::execute()" might add "int" as a native return type declaration in the future. Do the same in child class "Contentful\ContentfulBundle\Command\Delivery\DebugCommand" now to avoid errors or add an explicit @return annotation to suppress this message.
1. Method "Symfony\Component\HttpKernel\CacheWarmer\WarmableInterface::warmUp()" might add "array" as a native return type declaration in the future. Do the same in implementation "Contentful\ContentfulBundle\Cache\Delivery\CacheWarmer" now to avoid errors or add an explicit @return annotation to suppress this message.

**Comment by Sebb767** [comment]
Fixed with [7.1.1](https://github.com/contentful/ContentfulBundle/releases/tag/7.1.1)
